# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
[shell]
program = "zsh"
args = ["-c", "~/.scripts/startup_terminal.sh; exec /bin/zsh"]

[window]
dynamic_padding   = false
resize_increments = true
opacity           = 1

[window.dimensions]
columns = 80
lines   = 25

[font]
size = 9.0

[font.bold]
family = "0xProto Nerd Font"
style  = "Heavy"

[font.bold_italic]
family = "0xProto Nerd Font"
style  = "Heavy Italic"

[font.italic]
family = "0xProto Nerd Font"
style  = "Medium Italic"

[font.normal]
family = "0xProto Nerd Font"
style  = "Medium"

[cursor.style]
shape = "Beam"
blinking = "On"

[env]
term = "xterm-256color"
