# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'


[shell]
program = "zsh"
args = ["-c", "~/.scripts/startup_terminal.sh; exec /bin/zsh"]

[window]
dynamic_padding   = false
resize_increments = true
opacity           = 1

[window.dimensions]
columns = 80
lines   = 25

[font]
size = 9.0

[font.bold]
family = "0xProto Nerd Font"
style  = "Heavy"

[font.bold_italic]
family = "0xProto Nerd Font"
style  = "Heavy Italic"

[font.italic]
family = "0xProto Nerd Font"
style  = "Medium Italic"

[font.normal]
family = "0xProto Nerd Font"
style  = "Medium"

[cursor.style]
shape = "Beam"
blinking = "On"



