
# Colors (Hyper)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#808080'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#FFFFFF'

[shell]
program = "zsh"
args = ["-c", "~/.scripts/startup_terminal.sh; exec /bin/zsh"]

[window]
dynamic_padding   = false
resize_increments = true
opacity           = 1

[window.dimensions]
columns = 80
lines   = 25

[font]
size = 9.0

[font.bold]
family = "0xProto Nerd Font"
style  = "Heavy"

[font.bold_italic]
family = "0xProto Nerd Font"
style  = "Heavy Italic"

[font.italic]
family = "0xProto Nerd Font"
style  = "Medium Italic"

[font.normal]
family = "0xProto Nerd Font"
style  = "Medium"

[cursor.style]
shape = "Beam"
blinking = "On"



